# Generated by Django 4.2.8 on 2024-01-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
    ]
