# Generated by Django 4.2.8 on 2024-01-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_status_tickettype_tickets_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('expired', 'expired'), ('available', 'available')], default='available', max_length=50),
        ),
    ]
